
# open source
source 'https://github.com/CocoaPods/Specs.git'

# my work
source 'https://github.com/KeyFive/ZQPodSpec.git'

use_frameworks!

target 'ZQNetworkManager_Example' do
  pod 'ZQNetworkManager'

  target 'ZQNetworkManager_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
